### ISSUE TITLE
Action 'CreateFlightTeam' failed

### ISSUE THREAD

**Issue by mscollabdev** [microsoftgraph/contoso-airlines-azure-functions-sample#2]
When we insert a new item into the list the flow throws an error at step "CreateFlightTeam"

{"result":"failed","details":{"ClassName":"System.TypeInitializationException","Message":"The type initializer for 'create_flight_team.AuthProvider' threw an exception.","Data":null,"InnerException":{"ClassName":"System.ArgumentNullException","Message":"Value cannot be null.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential..ctor(String clientId, String clientSecret)\r\n   at create_flight_team.AuthProvider..cctor() in C:\\Akshay\\contoso_airlines\\contoso-airlines-azure-functions-sample-master\\create-flight-team\\AuthProvider.cs:line 13","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2147467261,"Source":"Microsoft.IdentityModel.Clients.ActiveDirectory","WatsonBuckets":"AQAAAEMATABSADIAMAByADMAA ......

,"ParamName":"clientId"},"HelpURL":null,"StackTraceString":"   at create_flight_team.AuthProvider.GetTokenOnBehalfOfAsync(String authHeader) in C:\\Akshay\\contoso_airlines\\contoso-airlines-azure-functions-sample-master\\create-flight-team\\AuthProvider.cs:line 35\r\n   at create_flight_team.CreateFlightTeam.Run(HttpRequest req, TraceWriter log) in C:\\Akshay\\contoso_airlines\\contoso-airlines-azure-functions-sample-master\\create-flight-team\\CreateFlightTeam.cs:line 39","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233036,"Source":"create-flight-team","WatsonBuckets":"AQAAAEMATABSADIAMAByADMAA","TypeName":"create_flight_team.AuthProvider"}}

**Comment by mscollabdev** [comment]
> That's a lot of error spew, but it looks like it's saying a value is null `at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential..ctor(String clientId, String clientSecret)`. I'm guessing that your `clientId` or `clientSecret` are null.
> 
> Are you running this locally or have you deployed it to Azure? If locally, you need to rename the local.settings.json.example file to local.settings.json and put your client ID and secret in there (and fill in the other fields).
> 
> If it's on Azure, then you need to set those values as environment variables for your function app. Specifically these values need to be set:
> 
> ```
> "TenantId": "YOUR TENANT ID HERE",
> "TenantName": "YOUR TENANT NAME HERE (contoso.onmicrosoft.com)",
> "AppId": "YOUR APP ID HERE",
> "AppSecret": "YOUR APP SECRET HERE",
> "TeamAppToInstall": "1542629c-01b3-4a6d-8f76-1938b779e48d",
> "FlightAdminSite": "FlightAdmin",
> "FlightLogFile": "Flight Log.docx",
> "NotificationAppId": "YOUR CROSS DEVICE EXPERIENCE HOST NAME"
> ```


Thank you for the quick reply. I have deployed my solution on Azure. I tried the above mentioned steps and now I am getting "Unauthorized" error on step CreateFlightTeam in the flow.

![image](https://user-images.githubusercontent.com/44091665/47483901-fe007f80-d857-11e8-9471-d980993c1600.png)


Here is how I entered the above values -

"TenantId": "My Azure Ad Tenant ID where my functions app & ad registrations are deployed",
"TenantName": "My Azure tenant name", (Please note my Azure ID and my O365 tenant Id are different)
"AppId": Flight Team Provisioning Connector App ID
"AppSecret": Flight Team Provisioning Connector App Secret
"TeamAppToInstall": "1542629c-01b3-4a6d-8f76-1938b779e48d",
"FlightAdminSite": "FlightAdmin",
"FlightLogFile": "Flight Log.docx",
"NotificationAppId": "YOUR CROSS DEVICE EXPERIENCE HOST NAME"

**Comment by jasonjoh** [comment]
Ok. I realize that the instructions I've got here are likely the reason you're running into issues. I've had it on my to-do list for weeks to update these to be a little more user-friendly!

The AppId and AppSecret that you have set as environment variables in Azure should be the ones for the Flight Team Provisioning Function. The AppId and AppSecret for the Flight Team Provisioning Connector are only used in [setting up the Flow connector](https://github.com/microsoftgraph/contoso-airlines-azure-functions-sample/blob/master/SETUP.md#add-custom-connector-for-azure-functions).

**Comment by mscollabdev** [comment]
Hi Jason, 

This solution worked like a charm! Thank you for all the help and guidance!
I will be grateful if you can share some more solutions like these which primarily use Microsoft Teams.
Appreciate your time and efforts.

Thanks & Regards,
Akshay
